name: pnpm packageManager Update

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

permissions: {}

jobs:
  update:
    permissions:
      contents: write
      pull-requests: write
      statuses: write
    uses: j7an/shared-workflows/.github/workflows/pnpm-packagemanager-update.yml@19391aa44c5b4f6247a38cf38c158fe692a44990 # v4.12.0
    with:
      minimum_release_age_days: 5
    secrets:
      RELEASE_BOT_PRIVATE_KEY: ${{ secrets.RELEASE_BOT_PRIVATE_KEY }}
